### ISSUE TITLE
Hello how can I create/update a confluence page from the R console ? 

### ISSUE THREAD

**Issue by statquant** [line/conflr#13]
Hello, I am using the [nvimr ](https://github.com/jalvesaq/Nvim-R)plugin and __not__ Rstudio.
I'd like to be able to create/update a confluence page from the R console.
I tried to do 
```
R> conflr::confl_create_post_from_Rmd(here::here("fi_aware.Rmd")) 
Error: RStudio not running
In addition: Warning message:
In stop(e, call. = FALSE) : additional arguments ignored in stop()
```
Is there a function I can use that would be like
```
conflr::confl_create_post_from_Rmd(Rmd_file, spaceId, username, ...)
```
that would allow me to work without any rstudio ?

**Comment by yutannihilation** [comment]
Hi, thanks for your feedback!

The error is caused by asking the base URL of your Confluence, your username and password. You can avoid it by setting the corresponding environmental variables. Please put the following in `~/.Renviron`:

``` r
CONFLUENCE_URL=https://confluence.example.com
CONFLUENCE_USERNAME=your_name
CONFLUENCE_PASSWORD=xxx
```

I'm aware that currently it's not confortable to use conflr outside RStudio and will address in #10. If you have some ideas, please comment there.

**Comment by statquant** [comment]
Thanks, publishing from R now works (from time to time) for me, FYI I think advising people in the docs to set their .Renviron with chmod 600 .Renviron would be advisable.

**Comment by yutannihilation** [comment]
Agreed, thanks.
