### ISSUE TITLE
Quarto support

### ISSUE THREAD

**Issue by fkgruber** [line/conflr#162]
What are the plans for supporting quarto?
Will it still be an R package? What if the quarto document has Julia or Python code?

thanks
FKG

**Comment by yutannihilation** [comment]
Hi, in short, conflr will never support Quarto, because Quarto is going to support Confluence. It's still in active development, but looks promising.

https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/extensions/quarto/confluence
https://github.com/quarto-dev/quarto-cli/tree/main/src/publish/confluence
