### ISSUE TITLE
Option to turn off "Notify watchers" 

### ISSUE THREAD

**Issue by kaliszp** [line/conflr#20]
Hi,

First of - 'conflr' is a real time saver for me!
Your work is appreciated!

I am facing similar issue are described here:
https://jira.atlassian.com/browse/CONFSERVER-38804

i.e. watchers are being notifed not only when I post new page but also when I add content or modify it. This seems to be resulting in sending notification  each time I invoke knitr::include_graphics().
According to the link provided this ca be partially solved by using "minorEdit" : true .
Do you plan on implementing it or having any other workaround for the problem ?

Best regards,
P.

**Comment by yutannihilation** [comment]
Thanks, I didn't know that option! It seems easy to implement this. I will try.

Note to self: add `minorEdit` option to [here](https://github.com/line/conflr/blob/d05c8f8057a65ae394be993711526aa03d830d12/R/content.R#L102)

``` json
    "version": {
        "number": 2,
        "minorEdit": false,
        "hidden": false
    },
```

**Comment by yutannihilation** [comment]
@kaliszp I added an "Notify watchers" option. Could you confirm this works?

<img width="650" alt="スクリーンショット 2019-03-14 11 24 19" src="https://user-images.githubusercontent.com/1978793/54326959-bb471480-464b-11e9-8391-def17b6c9434.png">

**Comment by kaliszp** [comment]
@yutannihilation 
Thanks for the update, however when I post page (with "Notify watchers" unticked) with 2 images, watchers still get 3 notifications.
This seems to be Confluence problem - "notify watchers" concerns creating page. However for automatically adding content, there is no option in REST API to not notify watchers. Strangely enough if you add content manually and untick notify watchers then there is no notification sent.

All in all - yutannihilation, I really appreciate your work!

**Comment by yutannihilation** [comment]
Opps..., thanks for testing and the information.

I thought `minorEdit` would work since it is described in this document: https://docs.atlassian.com/ConfluenceServer/rest/6.14.1/#api/content-update, but, from [the latest document](https://developer.atlassian.com/cloud/confluence/rest/#api-content-id-put), `minorEdit` seems available only on updating attachments.

I too think this is a problem on Confluence's side. Anyway I reopen this and wait for Confluence's update. Sorry for taking your time.

**Comment by daroczig** [comment]
After some local testing, #107 seems to fix this for me -- can you folks please check as well?

**Comment by yutannihilation** [comment]
Thanks, your pull request looks good to me! And, now I found I misunderstood the original problem here... Maybe I needed to add `minorEdit` to `confl_post_attachment()` and `confl_update_attachment()` as well.

**Comment by daroczig** [comment]
Thanks @yutannihilation -- I've just updated that PR to pass the required checks, let me know if you need anything else to merge it.

**Comment by yutannihilation** [comment]
@daroczig
Thanks so much for your contribution! I've added some tweaks to add the option to attachment operations as well. Now I believe this issue can be closed at last! :tada:

@kaliszp 
> Thanks for the update, however when I post page (with "Notify watchers" unticked) with 2 images, watchers still get 3 notifications.

Though I closed this, I'm not sure if this really solves your problem because it seems to depend on the Confluence's version... For reference, I guess the 3 notifications were

* 1 for the update of the content
* 2 for the update of the attachments (images)

and I completely forgot to address the latter one on #23, sorry. I hope #108 suppresses the latter on your Confluence so that you can reduce the number of notifications to 1 per update, if not 0...
