### ISSUE TITLE
Will it be possible to publish html content as opposed to md to confluence

### ISSUE THREAD

**Issue by statquant** [line/conflr#27]
Given that html gives access to richer content than md (interactive graphs etc...)
Is it a goal to be able to publish html to confluence ?
Thanks

**Comment by yutannihilation** [comment]
No. Confluence has its own syntax, and it's not compatible either with HTML or Markdown. You might expect using HTML macro, but it's not always available as I wrote on https://github.com/line/conflr/issues/15#issuecomment-477645616. Sorry, I can do nothing here....

(I'll eventually switch internal implementation to use HTML instead of Markdown, but it's probably not what you want.)
